version: "3.8"

services:
  server:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:3000
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - animal_shelter_db_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  animal_shelter_db_data:
    external: true
