version: "3.8"

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db:
