version: "3.8"

services:
  server:
    image: lfwbh/server:latest
    restart: unless-stopped
    networks:
      - db
    env_file:
      - .env.prod
    ports:
      - 8080:3000
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    networks:
      - db
    volumes:
      - animal_shelter_db_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  animal_shelter_db_data:
    external: true

networks:
  db:
