import { PetResponse } from "modules/pets/application/swagger/PetResponse";

export default function getPetSchema() {
  return {
    type: "object",
    properties: {
      age: { type: "number" },
      archived: { type: "boolean" },
      archiveDate: { type: "string" },
      cameFrom: { type: "string" },
      color: { type: "string" },
      createdAt: { type: "string" },
      description: { type: "string" },
      dead: { type: "boolean" },
      id: { type: "number" },
      kind: { type: "string" },
      name: { type: "string" },
      passport: { type: "boolean" },
      reviewed: { type: "boolean" },
      sex: { type: "string" },
      special: { type: "boolean" },
      sterilizationDate: { type: "string" },
      sterilized: { type: "boolean" },
      updatedAt: { type: "string" },
    } as Record<keyof PetResponse, any>,
    required: [
      "age",
      "archived",
      "archiveDate",
      "cameFrom",
      "color",
      "createdAt",
      "description",
      "dead",
      "id",
      "kind",
      "name",
      "passport",
      "reviewed",
      "sex",
      "special",
      "sterilizationDate",
      "sterilized",
      "updatedAt",
    ] as Array<keyof PetResponse>,
  };
}
